### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by aurora7795** [mark-wade/homebridge-hive#1]
Have had a try of adding this plugin to my existing functioning home bridge setup. Have managed to get an Orvibo S20 running ok but when adding your accessory addition to the config after installing your plugin, i'm getting the following error:

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hive/index.js:52:20)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-hive/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hive/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hive/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)

I have thrown my config through JSONlint to check it was ok and it doesn't seem to be upset with it - any ideas what might be wrong? (config attached)

(remove txt extension)

**Comment by aurora7795** [comment]
[config.json.txt](https://github.com/mark-wade/homebridge-hive/files/691192/config.json.txt)

**Comment by mark-wade** [comment]
I think your configuration is right. It looks like their API is either having issues or they've changed it - I'm seeing a similar thing and their API is returning a 503 (Service Unavailable) response.

I will check it again in a day or so to see if it's just a temporary thing or if I need to work around it.

**Comment by aurora7795** [comment]
I saw something on the HiveKit GitHub that seemed to indicate that certificates had changed recently, it might be worth having a look at the issue tracker on that project to see what problems they've been having

**Comment by mark-wade** [comment]
Should be fixed now.
