### ISSUE TITLE
Crash after a few days

### ISSUE THREAD

**Issue by EssendonPhoto** [mark-wade/homebridge-hive#7]
Hi - the new version (2 thermostats) has worked well for a few days. But then this evening ...

/usr/local/lib/node_modules/homebridge-hive/index.js:174
					this.log( "Current temperature is " + data.attributes.temperature.reportedValue );
					                                          ^

TypeError: Cannot read property 'attributes' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hive/index.js:174:48)
    at Object.getMainData (/usr/local/lib/node_modules/homebridge-hive/index.js:84:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hive/index.js:173:10)
    at emitThree (events.js:116:13)
    at emit (events.js:194:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:634:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:598:8)
    at emitMany (events.js:127:13)

**Comment by mark-wade** [comment]
Hmm... was there anything in the log before that? After "Fetching data from Hive API"?

**Comment by EssendonPhoto** [comment]
Sorry - didn't keep the log file. I will post both logs if it happens again.

**Comment by EssendonPhoto** [comment]
No recurrence to date. I suggest you close this issue and I will post again with logs if it recurs.

PS Did you decide not to include Hot Water?

**Comment by mark-wade** [comment]
I have a combi boiler so I don't have a way to test hot water support.
